export default {
  CHANGE_TRANSACTION_TYPE_FILTER: 'CHANGE_TRANSACTION_TYPE_FILTER',
  CHANGE_DATE_FILTER: 'CHANGE_DATE_FILTER',
  CHANGE_CATEGORY_FILTER: 'CHANGE_CATEGORY_FILTER',
  CHANGE_ACCOUNTS_FILTER: 'CHANGE_ACCOUNTS_FILTER',
};
