export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHANGE_ITEM_LABEL = 'CHANGE_ITEM_LABEL';
export const CHANGE_ITEM_AMOUNT = 'CHANGE_ITEM_AMOUNT';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const UPDATE_NET_INCOME = 'UPDATE_NET_INCOME';
export const UPDATE_LEFTOVER = 'UPDATE_LEFTOVER';
