/*
* TRIAL BALANCE
*/
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHANGE_ITEM_LABEL = 'CHANGE_ITEM_LABEL';
export const CHANGE_ITEM_AMOUNT = 'CHANGE_ITEM_AMOUNT';
export const RECALCULATE_SECTION_TOTAL = 'RECALCULATE_SECTION_TOTAL';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
/*
* TOTALS
*/
export const RECALCULATE_ASSETS_TOTAL = 'RECALCULATE_ASSETS_TOTAL';
export const RECALCULATE_EXPENSES_TOTAL = 'RECALCULATE_EXPENSES_TOTAL';
export const RECALCULATE_LIABILITIES_TOTAL = 'RECALCULATE_LIABILITIES_TOTAL';
export const RECALCULATE_GOALS_TOTAL = 'RECALCULATE_GOALS_TOTAL';
export const UPDATE_NET_INCOME = 'UPDATE_NET_INCOME';
export const UPDATE_LEFTOVER = 'UPDATE_LEFTOVER';
