export const ADD_ASSET = 'ADD_ASSET';
export const REMOVE_ASSET = 'REMOVE_ASSET';
export const MODIFY_ASSET_LABEL = 'MODIFY_ASSET_LABEL';
export const MODIFY_ASSET_AMOUNT = 'MODIFY_ASSET_AMOUNT';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const MODIFY_EXPENSE_LABEL = 'MODIFY_EXPENSE_LABEL';
export const MODIFY_EXPENSE_AMOUNT = 'MODIFY_EXPENSE_AMOUNT';

export const ADD_LIABILITY = 'ADD_LIABILITY';
export const REMOVE_LIABILITY = 'REMOVE_LIABILITY';
export const MODIFY_LIABILITY_LABEL = 'MODIFY_LIABILITY_LABEL';
export const MODIFY_LIABILITY_AMOUNT = 'MODIFY_LIABILITY_AMOUNT';

export const ADD_GOAL = 'ADD_GOAL';
export const REMOVE_GOAL = 'REMOVE_GOAL';
export const MODIFY_GOAL_LABEL = 'MODIFY_GOAL_LABEL';
export const MODIFY_GOAL_AMOUNT = 'MODIFY_GOAL_AMOUNT';
