export default {

    FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
    HYDRATE_STORE: 'HYDRATE_STORE',
    LOADING_TRANSACTIONS: 'LOADING_TRANSACTIONS',
    TRANSACTIONS_FETCH_SUCCESS: 'TRANSACTIONS_FETCH_SUCCESS',
    TRANSACTIONS_FETCH_FAILURE: 'TRANSACTIONS_FETCH_FAILURE',
    HYDRATE_TRANSACTIONS_STATE: 'HYDRATE_TRANSACTIONS_STATE',
    SET_DEFAULT_TRANSACTIONS_DATE_RANGE: 'SET_DEFAULT_TRANSACTIONS_DATE_RANGE',
    CHANGE_DATE_RANGE: 'CHANGE_DATE_RANGE'
}
