export default {

    CATEGORIZE_TRANSACTIONS: 'CATEGORIZE_TRANSACTIONS',
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE'
}
